### PR TITLE
add other clean web scrapes

### PR DESCRIPTION
**Pull request by Timilehin**
This PR adds more clean yoruba data from some news sites and other websites

@ruohoruotsi @dadelani

### CODE REVIEW

**Comment by ruohoruotsi** [comment]
I need to add a style-guide or a document to canonicalize the format for this repo. In the meantime, will defer that work to a separate issue.

**Comment by Timilehin** [comment]
Agree. I made a small script to validate properties of the data in the other PR. I can add stuff to the script to enforce the syle guide

**Comment by ruohoruotsi** [comment]
@Timilehin This is the PR in question .. re: the origin of `news_site` scraping

**Comment by ruohoruotsi** [comment]
@Timilehin has provided the following links as sources of the news_sites:
- https://www.theyorubablog.com/o%E1%B9%A3elu-nigeria-e-jowo-e-ma-pe-aja-ni-obo-fun-ara-ilu-pleading-with-the-nigerian-po/
- https://yo.wikipedia.org/wiki/Wikipedia:%C3%80y%E1%BB%8Dk%C3%A0_%E1%BB%8D%E1%B9%A3%E1%BA%B9%CC%80_37_%E1%BB%8Dd%C3%BAn_2017
- https://www.facebook.com/YORUBADUNNKA/?hc_ref=ARSde8yXkDyLK2flgs7Ckt-fva3BHlgVsovlWSHUlEV3F-Lcw1UMjHJ4K2lzev5uKwg&fref=nf&__tn__=kC-R

One note @dadelani has mentioned that he excluded it from his embedding work due to it's noise (likely Wikipedia). So when using, consider if those sources make sense for your usecase. Or better consider cleaning it and submitting a PR!
Thank you!

**Pull request merged**
